version: '3'

services:
  payment_app:
    build: ./payment-app/.
    image: payment_app_image
    ports:
      - 4040:4040
    environment:
      NODE_ENV: 'development'
      ORDER_APP_URL: 'http://localhost:4000'
      # ORDER_APP_URL: order_app
    network_mode: "host"

  order_app:
    build: ./order-app/.
    image: order_app_image
    ports:
      - 4000:4000
    environment:
      NODE_ENV: 'development'
      POSTGRESQL_CONNECTION_STRING: 'postgres://rjujizsf:h19hXxBwzen8SxIS_V04XYnbagaevnTK@john.db.elephantsql.com/rjujizsf'
      PAYMENT_APP_URL: 'http://localhost:4040'
      # PAYMENT_APP_URL: payment_app
    network_mode: "host"

  # order_portal:
  #   build: ./order-portal/.
  #   image: order_portal_image
  #   ports:
  #     - 3000:80
  #   environment:
  #     NODE_ENV: 'development'
  #     REACT_APP_ORDER_APP_URL: "http://localhost:4000"
  #     REACT_APP_USER_ID: "3432323-332323-423432323"
  #   # network_mode: "host"

  
  order_portal:
    build: 
      context: ./order-portal/.
      dockerfile: ./Dockerfile.dev
    image: order_portal_image_dev
    ports:
      - 3000:3000
    environment:
      NODE_ENV: 'development'
      REACT_APP_ORDER_APP_URL: "http://localhost:4000"
      # REACT_APP_ORDER_APP_URL: order_app
      REACT_APP_USER_ID: "3432323-332323-423432323"
    network_mode: "host"


# networks:
#   default: