version: '3'

services:
  payment_app:
    container_name: payment_app
    image: payment_app_image
    ports:
      - 4040:4040
    environment:
      NODE_ENV: 'development'
      ORDER_APP_URL: 'http://localhost:4000'
    network_mode: "host"
