version: '3'

services:
  payment_app:
    container_name: payment_app
    image: payment_app_image
    ports:
      - 4040:4040
    environment:
      NODE_ENV: 'development'
      ORDER_APP_URL: 'http://localhost:4000'
    network_mode: "host"

  order_app:
    container_name: order_app
    image: order_app_image
    ports:
      - 4000:4000
    environment:
      NODE_ENV: 'development'
      POSTGRESQL_CONNECTION_STRING: 'postgres://rjujizsf:h19hXxBwzen8SxIS_V04XYnbagaevnTK@john.db.elephantsql.com/rjujizsf'
      PAYMENT_APP_URL: 'http://localhost:4040'
    network_mode: "host"

